
/**
* PeerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Peer.idl
* domingo 15 de mayo de 2022 08:23:28 PM CDT
*/

public interface PeerOperations 
{
  void enviar_Mensaje (String mensaje);
  void actualizar_Lista_Peers (String peers);
  void updateCoor (String coor);
  void startElection (String nodeId, String id);
  void sendOk (String where, String to);
  void iWon (String node);
  boolean isalive ();
  String getCoordinator ();
} // interface PeerOperations
