interface Peer
{
    void enviar_Mensaje(in string mensaje);
    string getIdPeer();
    void actualizar_Lista_Peers(in string peers);
    void updateCoordinator(in string coor);
    void startElection(in string nodeId);
    void sendOk(in string where, in string to);
    void iWon(in string node);
    boolean isalive();
    string getCoordinator();
};