
/**
* Peer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Peer.idl
* domingo 15 de mayo de 2022 08:23:28 PM CDT
*/

public interface Peer extends PeerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Peer
