
/**
* Peer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Peer.idl
* martes 17 de mayo de 2022 01:19:05 AM CDT
*/

public interface Peer extends PeerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Peer
